In [1]:
import numpy as np
import tensorflow as tf

def sigmoid(x):
    return 1/(1+np.exp(-x))

data_x1 = np.array([[0., 1.], [1, 0], [1, 1], [0, -1], [-1, 0], [-1, -1], [-1,-1]])
data_x2 = np.array([[1., 0.], [-1, 1], [0, -2], [2, 1], [1, -1], [2, 2], [1, 1]])

## Numpy version

output = new_state = act(W * input + U * state + B).

In [2]:
npW = np.array([[-1.], [2.]])
npU = np.array([[4.]])
npB = np.array([-1.])

state_1 = sigmoid(np.matmul(data_x1, npW) + npB)
print(state_1)

state_2 = sigmoid(np.matmul(data_x2, npW) + np.matmul(state_1, npU) + npB)
print(state_2)

[[ 0.73105858]
 [ 0.11920292]
 [ 0.5       ]
 [ 0.04742587]
 [ 0.5       ]
 [ 0.11920292]
 [ 0.11920292]]
[[ 0.71590409]
 [ 0.92250016]
 [ 0.04742587]
 [ 0.30782732]
 [ 0.11920292]
 [ 0.81409052]
 [ 0.61699472]]


## The same with tensorflow

In [3]:
input_1 = tf.placeholder(tf.float32, shape=[None, 2], name='input_1') 
input_2 = tf.placeholder(tf.float32, shape=[None, 2], name='input_2')
    

with tf.name_scope('rec1_layer'):
    tfW = tf.constant([[-1.], [2.]], dtype=tf.float32)
    tfU = tf.constant([[4.]], dtype=tf.float32)
    tfB = tf.constant([-1.], dtype=tf.float32)
    state_1 = tf.nn.sigmoid(tf.matmul(input_1, tfW) + tfB)
    
with tf.name_scope('rec2_layer'):
    state_2 = tf.nn.sigmoid(tf.matmul(input_2, tfW) + tf.matmul(state_1, tfU) + tfB)

In [4]:
feed_dict = {input_1: data_x1, input_2: data_x2}
with tf.Session() as sess:
    writer = tf.summary.FileWriter('logs/03')
    writer.add_graph(sess.graph)
    print(sess.run(state_2, feed_dict))

[[ 0.71590412]
 [ 0.92250019]
 [ 0.04742587]
 [ 0.30782729]
 [ 0.11920292]
 [ 0.81409055]
 [ 0.61699468]]


## Another version

[[ 0.71590412]
 [ 0.92250019]
 [ 0.04742587]
 [ 0.30782729]
 [ 0.11920292]
 [ 0.81409055]
 [ 0.61699468]]
