# Basic RNN

http://colah.github.io/posts/2015-08-Understanding-LSTMs/

In [7]:
import numpy as np
import tensorflow as tf

data_x1 = np.array([[0., 1.], [1, 0], [1, 1], [0, -1], [-1, 0], [-1, -1], [-1,-1]])
data_x2 = np.array([[1., 0.], [-1, 1], [0, -2], [2, 1], [1, -1], [2, 2], [1, 1]])

![title](imgs/LSTM3-SimpleRNN.png)

output = new_state = act(W * input + U * state + B).

## Numpy version


In [8]:
npW = np.array([[-1.], [2.]])
npU = np.array([[4.]])
npB = np.array([-1.])

state_1 = np.tanh(np.matmul(data_x1, npW) + npB)
print(state_1)

state_2 = np.tanh(np.matmul(data_x2, npW) + np.matmul(state_1, npU) + npB)
print(state_2)

[[ 0.76159416]
 [-0.96402758]
 [ 0.        ]
 [-0.99505475]
 [ 0.        ]
 [-0.96402758]
 [-0.96402758]]
[[ 0.78039367]
 [-0.95231809]
 [-0.9999092 ]
 [-0.99990554]
 [-0.9993293 ]
 [-0.99341113]
 [-0.99910575]]


## The same with tensorflow

In [9]:
input_1 = tf.placeholder(tf.float32, shape=[None, 2], name='input_1') 
input_2 = tf.placeholder(tf.float32, shape=[None, 2], name='input_2')
    

with tf.name_scope('rec1_layer'):
    tfW = tf.constant([[-1.], [2.]], dtype=tf.float32)
    tfU = tf.constant([[4.]], dtype=tf.float32)
    tfB = tf.constant([-1.], dtype=tf.float32)
    state_1 = tf.nn.tanh(tf.matmul(input_1, tfW) + tfB)
    
with tf.name_scope('rec2_layer'):
    state_2 = tf.nn.tanh(tf.matmul(input_2, tfW) + tf.matmul(state_1, tfU) + tfB)

In [10]:
feed_dict = {input_1: data_x1, input_2: data_x2}
with tf.Session() as sess:
    writer = tf.summary.FileWriter('logs/03')
    writer.add_graph(sess.graph)
    print(sess.run(state_2, feed_dict))

[[ 0.78039378]
 [-0.95231807]
 [-0.99990916]
 [-0.99990541]
 [-0.99932921]
 [-0.99341124]
 [-0.99910557]]
