In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6]])
b = np.array([[11, 12, 13], [12, 13, 14], [13, 14, 15], [16, 17, 18]])


In [9]:
c = np.array([a, b])
c

array([[[ 1,  2,  3],
        [ 2,  3,  4],
        [ 3,  4,  5],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [12, 13, 14],
        [13, 14, 15],
        [16, 17, 18]]])

In [23]:
np.transpose(c)

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 16]],

       [[ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 17]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 18]]])

In [28]:
np.transpose(c, axes=[2, 1, 0])

array([[[ 1, 11],
        [ 2, 12],
        [ 3, 13],
        [ 4, 16]],

       [[ 2, 12],
        [ 3, 13],
        [ 4, 14],
        [ 5, 17]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15],
        [ 6, 18]]])

In [30]:
a = np.array([[1], [2], [3], [4]])
b = np.array([[11], [12], [13], [16]])
c = np.array([a, b])
c

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[11],
        [12],
        [13],
        [16]]])

In [50]:
np.transpose(c, axes=[2, 1, 0])[0]

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 16]])

In [53]:
ctrans = np.reshape(np.transpose(c, axes=[2, 1, 0])[0], (-1, 2, 1))

In [55]:
ctrans.shape

(4, 2, 1)

In [60]:
a = np.array([[1, 2, 3], [12, 13, 14], [23, 24, 25], [34, 35, 36]])
print(a.shape)
a

(4, 3)


array([[ 1,  2,  3],
       [12, 13, 14],
       [23, 24, 25],
       [34, 35, 36]])

In [61]:
a.transpose()

array([[ 1, 12, 23, 34],
       [ 2, 13, 24, 35],
       [ 3, 14, 25, 36]])

In [66]:
a.transpose().reshape((-1, 4, 1))

array([[[ 1],
        [12],
        [23],
        [34]],

       [[ 2],
        [13],
        [24],
        [35]],

       [[ 3],
        [14],
        [25],
        [36]]])