In [1]:
import numpy as np
import tensorflow as tf

In [24]:
x = tf.placeholder(tf.float32, (None, None))
y1 = tf.strided_slice(x, [0, 0], [2, 2], [1, 1])
y2 = tf.strided_slice(x, [0, 0], [6, 4], [2, 1])
y1_slice = tf.slice(x, [0,0], [2, 2])
y3_slice = tf.slice(x, [0,0], [2, -1]) 
#that includs -1  
y3 = tf.strided_slice(x, [0,0], [2, -1], [1, 1]) 


In [27]:
init = tf.global_variables_initializer()

n, m = 10, 6
feed_dict1 = {x: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}
feed_dict2 = {x: np.reshape(np.array(range(n * m)), (n, m))}


with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x, feed_dict1))
    print(sess.run(y1, feed_dict1))
    print(sess.run(y1_slice, feed_dict1))
    print(sess.run(x, feed_dict2))
    print(sess.run(y2, feed_dict2))
    print(sess.run(y3, feed_dict2))
    print(sess.run(y3_slice, feed_dict2))

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
[[ 1.  2.]
 [ 4.  5.]]
[[ 1.  2.]
 [ 4.  5.]]
[[  0.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]
 [ 12.  13.  14.  15.  16.  17.]
 [ 18.  19.  20.  21.  22.  23.]
 [ 24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.]
 [ 36.  37.  38.  39.  40.  41.]
 [ 42.  43.  44.  45.  46.  47.]
 [ 48.  49.  50.  51.  52.  53.]
 [ 54.  55.  56.  57.  58.  59.]]
[[  0.   1.   2.   3.]
 [ 12.  13.  14.  15.]
 [ 24.  25.  26.  27.]]
[[  0.   1.   2.   3.   4.]
 [  6.   7.   8.   9.  10.]]
[[  0.   1.   2.   3.   4.   5.]
 [  6.   7.   8.   9.  10.  11.]]
